
TF_DICTIONARY = "/tf_dictionary"
LOC_DICTIONARY = "/loc_dictionary"
INV_LOC_DICTIONARY = "/inv_loc_dictionary"
TRAINING_DATA = "/training_data"
TEXTIFIED_DATA = "/text_whitespace_separated"
MC_MODEL = "/model.h5"
AE_MODEL = "/ae/"
VAE_MODEL = "/vae/"
DISCOVERY_MODEL = "/discoverymodel.h5"
FQA_MODEL = "/fqa/"
VIS_OUTPUT = "test.pdf"
BAE_MODEL = "/bae/"
